MODULE idl_shadow
DESCRIPTION Link the new version of shadow to idl
VERSION 1.0
SOURCE Niccolo Canestrari
BUILD_DATE DECEMBER 2010
FUNCTION GENSOURCEGEOM 1 1
FUNCTION GENSOURCESYNC 1 1
FUNCTION TRACEOE 3 3
PROCEDURE PRINTSOURCE 2 2
PROCEDURE PRINTOE 2 2

